# Generated by Django 4.2.11 on 2025-04-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_teacherprofile_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='classrom',
            new_name='classroom',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10),
        ),
    ]
