# Generated by Django 4.2.11 on 2025-04-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a unique role name', max_length=255, unique=True, verbose_name='Role Name')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Creater At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
    ]
