# Generated by Django 4.2.11 on 2025-04-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('principal', 'Principal'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], help_text='Enter a unique role name', max_length=255, unique=True, verbose_name='Role Name'),
        ),
    ]
