# Generated by Django 4.2.11 on 2025-04-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_role_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='District Name')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Enter a unique role name', max_length=255, unique=True, verbose_name='Role Name'),
        ),
    ]
