# Generated by Django 4.2.11 on 2025-04-23 08:36

from django.db import migrations, models
import django.db.models.deletion
import role.models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0004_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Class Name')),
                ('grade_level', models.IntegerField(validators=[role.models.validate_grade_level])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='School_Classes', to='role.school')),
            ],
            options={
                'unique_together': {('name', 'school')},
            },
        ),
    ]
