# Generated by Django 4.2.11 on 2025-04-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0006_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_class',
        ),
        migrations.AddField(
            model_name='teacher',
            name='assigned_classes',
            field=models.ManyToManyField(related_name='class_teacher', to='role.class'),
        ),
    ]
