# Generated by Django 4.2.11 on 2025-04-24 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0008_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', message='Name must contain only letters and spaces.')], verbose_name='student Name'),
        ),
    ]
