# Generated by Django 4.2.11 on 2025-04-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0010_alter_teacher_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='assigned_classes',
            new_name='assigned_classess',
        ),
    ]
