# Generated by Django 4.2.11 on 2025-04-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0011_rename_assigned_classes_teacher_assigned_classess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='assigned_classess',
            new_name='assigned_classes',
        ),
    ]
