# Generated by Django 4.2.11 on 2025-04-24 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0012_rename_assigned_classess_teacher_assigned_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='School_Teacher', to='role.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='Not Assigned', max_length=255),
            preserve_default=False,
        ),
    ]
