# Generated by Django 4.2.11 on 2025-04-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0013_teacher_school_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.CharField(default='asif', max_length=255),
            preserve_default=False,
        ),
    ]
