# Generated by Django 4.2.11 on 2025-04-24 21:55

import assignments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0013_teacher_school_alter_teacher_subject'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='role.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=assignments.models.submission_file_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'submitted_by')},
        ),
        migrations.RemoveField(
            model_name='submission',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='student',
        ),
    ]
