# Generated by Django 4.2.11 on 2025-04-21 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_classrom_studentprofile_classroom_and_more'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignemntMark',
            new_name='AssignementMark',
        ),
    ]
