# Generated by Django 4.2.11 on 2025-05-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('assignments', '0002_alter_assignmentquestionthrough_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentquestion',
            name='assigned_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='role.class'),
        ),
    ]
