# Generated by Django 4.2.11 on 2025-05-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('assignments', '0003_assignmentquestion_assigned_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentquestion',
            name='assigned_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='role.class'),
            preserve_default=False,
        ),
    ]
