# Generated by Django 4.2.11 on 2025-04-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_rename_assignementmark_assignmentmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='classrom',
            new_name='classroom',
        ),
    ]
