# Generated by Django 4.2.11 on 2025-04-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rename_classrom_assignment_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_time',
            field=models.TimeField(default='23:59:00'),
        ),
    ]
